---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "fedora"

  - name: install apache2 package
    yum: 
      name: apache2
      state: latest
    when: ansible_distribution == "fedora"

  - name: add php support for apache
    yum:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "fedora"